# Optimizing a Supply Chain

Aung Si<br>
January 23<sup>rd</sup>, 2024

---

## Problem Breakdown 

**Objective:** Minimize Order Fulfilment Costs

Fulfilment costs are broken down into:
- Storage costs
- Freight costs

\begin{aligned}
\text{total fulfilment cost } (\mathbb{C}) = \text{total transportation cost } (\mathbf{T}) + \text{total storage cost } (\mathbf{S})
\end{aligned}

\begin{aligned}

\sum^m_{i=1}Q_{ij} (T_{ijr} + S_{ijp})
\end{aligned}

In [1]:
import pandas as pd

pd.read_csv("workflow/data/FreightRates.csv")

,Unnamed: 0,Carrier,orig_port_cd,dest_port_cd,minm_wgh_qty,max_wgh_qty,svc_cd,minimum cost,rate,mode_dsc,tpt_day_cnt,Carrier type
0,0,V444_6,PORT08,PORT09,250.0,499.99,DTD,43.2272,0.7132,AIR,2,V88888888_0
1,1,V444_6,PORT08,PORT09,65.0,69.99,DTD,43.2272,0.7512,AIR,2,V88888888_0
2,2,V444_6,PORT08,PORT09,60.0,64.99,DTD,43.2272,0.7892,AIR,2,V88888888_0
3,3,V444_6,PORT08,PORT09,50.0,54.99,DTD,43.2272,0.8272,AIR,2,V88888888_0
4,4,V444_6,PORT08,PORT09,35.0,39.99,DTD,43.2272,1.0552,AIR,2,V88888888_0
...,...,...,...,...,...,...,...,...,...,...,...,...
1535,1535,V444_8,PORT03,PORT09,0.0,99.99,DTD,29.3392,0.4116,AIR,0,V88888888_0
1536,1536,V444_8,PORT03,PORT09,500.0,1999.99,DTD,29.3392,0.3112,AIR,0,V88888888_0
1537,1537,V444_8,PORT03,PORT09,250.0,499.99,DTD,29.3392,0.4116,AIR,0,V88888888_0
1538,1538,V444_8,PORT03,PORT09,2000.0,99999.99,DTD,29.3392,0.3112,AIR,0,V88888888_0
1539,1539,V444_8,PORT03,PORT09,100.0,249.99,DTD,29.3392,0.4116,AIR,0,V88888888_0